apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nexus-gitops-application-set
  namespace: argocd
spec:
    project: nexus
    source:
        repoURL: https://github.com/thisisamank/nexus-gitops
        targetRevision: HEAD
        path: charts/deployment
        helm:
            valueFiles:
                - ../../apps/{{name}}/values.yaml
