  # qbittorrent:
  #   image: lscr.io/linuxserver/qbittorrent:latest
  #   container_name: qbittorrent
  #   restart: unless-stopped
  #   labels:
  #     - deunhealth.restart.on.unhealthy=true
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TZ}
  #     - WEBUI_PORT=8080 # must match "qbittorrent web interface" port number in gluetun's service above
  #     - TORRENTING_PORT=${FIREWALL_VPN_INPUT_PORTS} # airvpn forwarded port, pulled from .env
  #   volumes:
  #     - ./qbittorrent:/config
  #     - /data:/data
  #   depends_on:
  #     gluetun:
  #       condition: service_healthy
  #       restart: true
  #   network_mode: service:gluetun
  #   healthcheck:
  #     test: ping -c 1 www.google.com || exit 1
  #     interval: 60s
  #     retries: 3
  #     start_period: 20s
  #     timeout: 10s


image:
  repository: lscr.io/linuxserver/qbittorrent
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
    - host: qb.pixr.in
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: nexus-tls-prod
      hosts:
        - qb.pixr.in

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1024Mi

# FileBrowser does not require custom probes by default
livenessProbe: null
readinessProbe: null

# Pod labels and annotations
podLabels:
  app: qbittorrent
  version: v1

podAnnotations:
  description: "Download torrents"

volumes:
  - name: qbittorrent-root
    hostPath:
      path: /home/thisisamank/qbittorrent
      type: Directory
  - name: qbittorrent-data
    hostPath:
      path: /mnt/hetzner/data
      type: Directory
  # - name: vpn-files
  #   projected:
  #     sources:
  #       - secret:
  #           name: vpn-auth
  #           items:
  #             - key: auth.txt
  #               path: auth.txt
  #       - configMap:
  #           name: vpn-config-in-udp
  #           items:
  #             - key: in158.nordvpn.com.udp.ovpn
  #               path: nordvpn.ovpn

volumeMounts:
  - name: qbittorrent-root
    mountPath: /config
  - name: qbittorrent-data
    mountPath: /data

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

# sidecarContainers:
#   - name: openvpn-client
#     image: dperson/openvpn-client
#     securityContext:
#       privileged: true
#       capabilities:
#         add:
#           - NET_ADMIN
#     volumeMounts:
#       - name: vpn-files
#         mountPath: /vpn
#         readOnly: false
#     args:
#       # Enable the firewall kill switch
#       - "-f"
#       - ""
#       # Forward the torrenting port
#       - "-p"
#       - "6881"
