image:
  repository: filebrowser/filebrowser
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80


ingress:
  enabled: true
  className: "traefik"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: files.pixr.in
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: nexus-tls-prod
      hosts:
        - files.pixr.in

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

# FileBrowser does not require custom probes by default
livenessProbe: null
readinessProbe: null

# Pod labels and annotations
podLabels:
  app: filebrowser
  version: v1

podAnnotations:
  description: "Access files from the homelab using FileBrowser"

volumes:
  - name: filebrowser-root
    hostPath:
      path: /home/thisisamank/
      type: Directory

volumeMounts:
  - name: filebrowser-root
    mountPath: /srv
