#!/bin/bash

# Script to dynamically generate deployment chart values.yaml
# This script reads all YAML files from the deployment directory
# and generates the applications configuration

DEPLOYMENT_DIR="../../deployment"
VALUES_FILE="values.yaml"

echo "# Auto-generated values.yaml for deployment chart" > $VALUES_FILE
echo "# This file is generated by generate-values.sh script" >> $VALUES_FILE
echo "" >> $VALUES_FILE

echo "# Global configuration for all applications (used as defaults)" >> $VALUES_FILE
echo "global:" >> $VALUES_FILE
echo "  project: nexus" >> $VALUES_FILE
echo "  repoURL: https://github.com/thisisamank/nexus-gitops" >> $VALUES_FILE
echo "  targetRevision: HEAD" >> $VALUES_FILE
echo "  namespace: default" >> $VALUES_FILE
echo "  server: https://kubernetes.default.svc" >> $VALUES_FILE
echo "" >> $VALUES_FILE

echo "# Applications configuration" >> $VALUES_FILE
echo "# Each application is auto-discovered from the deployment directory" >> $VALUES_FILE
echo "applications:" >> $VALUES_FILE

# Find all app YAML files in deployment directory and process them
for file in $DEPLOYMENT_DIR/app-*.yaml; do
    if [ -f "$file" ]; then
        app_name=$(basename "$file" .yaml)
        echo "Processing $app_name..."

        # Extract values from the YAML file
        name=$(grep "^name:" "$file" | awk '{print $2}')
        project=$(grep "^project:" "$file" | awk '{print $2}')
        repoURL=$(grep "^repoURL:" "$file" | awk '{print $2}')
        targetRevision=$(grep "^targetRevision:" "$file" | awk '{print $2}')
        path=$(grep "^path:" "$file" | awk '{print $2}')
        valueFile=$(grep "^valueFile:" "$file" | awk '{print $2}')
        namespace=$(grep "^namespace:" "$file" | awk '{print $2}')
        server=$(grep "^server:" "$file" | awk '{print $2}')

        echo "  - name: $name" >> $VALUES_FILE
        echo "    project: $project" >> $VALUES_FILE
        echo "    repoURL: $repoURL" >> $VALUES_FILE
        echo "    targetRevision: $targetRevision" >> $VALUES_FILE
        echo "    path: $path" >> $VALUES_FILE
        echo "    valueFile: $valueFile" >> $VALUES_FILE
        echo "    namespace: $namespace" >> $VALUES_FILE
        echo "    server: $server" >> $VALUES_FILE
        echo "    # Additional application-specific overrides can be added here" >> $VALUES_FILE
        echo "    # syncPolicy:" >> $VALUES_FILE
        echo "    #   automated:" >> $VALUES_FILE
        echo "    #     prune: true" >> $VALUES_FILE
        echo "    #     selfHeal: true" >> $VALUES_FILE
        echo "" >> $VALUES_FILE
    fi
done

echo "Generated values.yaml with $(ls $DEPLOYMENT_DIR/app-*.yaml 2>/dev/null | wc -l) applications"
