---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: docker-registry-auth
  namespace: default
spec:
  encryptedData:
    htpasswd: AgAMOn4U/wf3u/IPRuxMu2zNEn8UBAGZpovC/7uTpeJNb0vBtsfJZJHfgvrH1hml+f+1IdRhD913p5bYh4/h+okgdRKbD2Fll7tXKRGoBLdVt9vrLKtzGNHEeXA1fr3TSLpD9PlKcxqziAqty8FicKlaAmj7eOv/XrQDSiuLJ0/EMLT0d5zoNWL9MnZ10KYMe2ezO0c/zUFDZXiu4KBjpEkRwA6G8Xg6M57NZmJuAFEVlQaPBBwsTUHg5RpNeQBrxWNmXF1bVFnv1/NbEG8jgGge/KMxNty3yx+4btL4NjmpuZ1OYEppDGBmqELJO+/ABRykP4ufA6CaSZ9kUVA0/U0sLcYA1HVUwg7n1a+9Fekq3CQj2GvOW7vH28W9MyOnm+XI4bxyPHyyluI5X5iJgKv0qUmaPrE1aVBiK84dhTXPJM3WzKm9J8WA6t9wmM3lVIkowTC9H95J/dJszMVFN/byY50RInEluefTeqtXmasgTPEj9SfEYeteHW6Qg/BfBm2yzIEYMvp1LxtoB3P+o0Z1tW63HR6sd4RUBk2cLWWW/eojzU7lMXxYczOdw7nG1b5mz1LR8PjJuuXjsaH/GtZdxjP39O1ogL5tUo1XJ6wdIxnN2tzZfvAN93N2IIhoa8NF+VE0m/aObCKJVn52ylLPNmeRNt6ErHzxa7aRJlG3ZwWO+yzYjIeWyzUCeu0U5HFvqhQpi8orq5vXUblm5y2hsA/KodcxtJTtVAMcCaSPrcL6W+ziyBW2kcBMRm0lVr0cyZHgtwVXDR8ImGPmPji1LIbuKttgCtJiVs/8r6/fJNDFB6Z6PEIaAXmjCA==
  template:
    metadata:
      name: docker-registry-auth
      namespace: default
    type: Opaque
